# how to create a function with data


# step 1. function definition 
def bnbrefund(acountnumber, refundamount): 
     print('account number:' + str(accountNumber))
     print('refund amount:'$ + str(refundamount))

# step 2. function call (invocation)
bnbrefund(19292929, 3000)



#my name is kadaeir and my birthday is oct 30.

def name_bday(name, bday):
     print('my name is + name + my nday is ' + bday)
name_bday('mary', 'july 2nd')

# my (13) dollae(s) is equal to (1300) pennies
def dollarconverters(dollar):
     pennies = dollar  * 100
     print('my ' +  str( dollar) +'s is equal to ' + str(pennies) + 'pennies ')



def area_of_triangles
print('area of triangle') 
length_height('20 ' + '23 ')  
length = 20
height = 23 
width  = 15
print(str'height = 23' 'width = 15 ' 'length = 20')